site_name: OPNsense Add-on for Splunk Documentation
edit_uri: edit/master/docs/
repo_url: https://github.com/ZachChristensen28/TA-opnsense
repo_name: ZachChristensen28/TA-opnsense
site_description: >-
  Welcome to the Home of the OPNsense Add-on for Splunk documentation. The OPNsense Add-on allows Splunk data administrators to map the OPNsense® Firewall events to the CIM enabling the data to be used with other Splunk Apps, such as the OPNsense App for Splunk.

plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.caret
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  logo: images/opn_ta_logo.png
  favicon: images/opn_ta_logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    # - header.autohide
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    # - toc.integrate
    - navigation.tracking
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/zachary-christensen28/
    - icon: fontawesome/brands/github
      link: https://github.com/ZachChristensen28
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ZachTheSplunker

copyright: Copyright &copy; 2023 ZachTheSplunker

nav:
  - Home: index.md
  - OPNsense Add-on: landing-page.md
  - Getting Started:
      - Logging Architecture: getting-started/logging-architecture.md
      - Where to Install: getting-started/where-to-install.md
      - Prerequisites: getting-started/prerequisites.md
      - Configure Inputs:
          - Configure Universal Forwarder: getting-started/configure-inputs/configure-inputs.md
          - Configure Modular Input: getting-started/configure-inputs/configure-modinput.md
      - Enrichment:
          - Configure Enrichment: getting-started/configure-enrichment.md
      - Troubleshooting:
          - Troubleshoot Monitoring Inputs: getting-started/troubleshooting/troubleshoot-inputs.md
          - Troubleshoot Modular Inputs: getting-started/troubleshooting/troubleshoot-modinputs.md
  - Guides:
      - Syslog Configuration: guides/guide-syslog.md
      - Intrusion Detection Logging: guides/guide-intrusion-detection.md
      - Index Utilization: guides/guide-index-utilization.md
      #- 'Collect Netflows': guides/guide-collect-netflows.md
  - Reference:
      - Sourectypes: reference/reference-sourcetypes.md
      - Modular Input Reference: reference/reference-mod-input.md
      - Changelog:
          - Release Notes: reference/releases/index.md
          - Release History: reference/releases/release-history.md
